
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Tips of exception handling in Ruby</title>
    <meta name="description" content="">

    <meta name="HandheldFriendly" content="True">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="../favicon.ico">

    <link rel="stylesheet" type="text/css" href="../assets/css/screen.css?v=d91b2f636f">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Merriweather:300,700,700italic,300italic%7COpen+Sans:700,400">

    <link rel="canonical" href="index.html">
    <meta name="referrer" content="origin">
    
    <meta property="og:site_name" content="A geeky corner">
    <meta property="og:type" content="article">
    <meta property="og:title" content="Tips of exception handling in Ruby">
    <meta property="og:description" content="In this post, I'd like to share with you some basic knowledge and tips about exception handling in Ruby. Avoiding rescue with Exception One common mistake when handling exceptions in Ruby is catching exceptions with an Exception instance, e.g rescue Exception =&amp;gt; e. The reason is very simple, let">
    <meta property="og:url" content="http://localhost:2368/tips-of-exception-handling-in-ruby/">
    <meta property="article:published_time" content="2015-01-01T18:32:00.000Z">
    <meta property="article:modified_time" content="2016-07-08T13:58:27.614Z">
    <meta property="article:tag" content="ruby">
    
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Tips of exception handling in Ruby">
    <meta name="twitter:description" content="In this post, I'd like to share with you some basic knowledge and tips about exception handling in Ruby. Avoiding rescue with Exception One common mistake when handling exceptions in Ruby is catching exceptions with an Exception instance, e.g rescue Exception =&amp;gt; e. The reason is very simple, let">
    <meta name="twitter:url" content="http://localhost:2368/tips-of-exception-handling-in-ruby/">
    <meta name="twitter:label1" content="Written by">
    <meta name="twitter:data1" content="Vinh Bach">
    <meta name="twitter:label2" content="Filed under">
    <meta name="twitter:data2" content="ruby">
    
    <script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Article",
    "publisher": {
        "@type": "Organization",
        "name": "A geeky corner",
        "logo": "http://localhost:2368/ghost/img/ghosticon.jpg"
    },
    "author": {
        "@type": "Person",
        "name": "Vinh Bach",
        "image": "//www.gravatar.com/avatar/a8637bb35bf705a7a5e7f5e69c67b784?s=250&d=mm&r=x",
        "url": "http://localhost:2368/author/vinh/",
        "sameAs": []
    },
    "headline": "Tips of exception handling in Ruby",
    "url": "http://localhost:2368/tips-of-exception-handling-in-ruby/",
    "datePublished": "2015-01-01T18:32:00.000Z",
    "dateModified": "2016-07-08T13:58:27.614Z",
    "keywords": "ruby",
    "description": "In this post, I&#x27;d like to share with you some basic knowledge and tips about exception handling in Ruby. Avoiding rescue with Exception One common mistake when handling exceptions in Ruby is catching exceptions with an Exception instance, e.g rescue Exception &#x3D;&amp;gt; e. The reason is very simple, let"
}
    </script>

    <meta name="generator" content="Ghost 0.8">
    <link rel="alternate" type="application/rss+xml" title="A geeky corner" href="../rss/index.html">
</head>
<body class="post-template tag-ruby nav-closed">

    <div class="nav">
    <h3 class="nav-title">Menu</h3>
    <a href="index.html#" class="nav-close">
        <span class="hidden">Close</span>
    </a>
    <ul>
            <li class="nav-home" role="presentation"><a href="../">Home</a></li>
    </ul>
        <a class="subscribe-button icon-feed" href="../rss/index.rss">Subscribe</a>
</div>
<span class="nav-cover"></span>


    <div class="site-wrapper">

        


<header class="main-header post-head no-cover">
    <nav class="main-nav  clearfix">
        
            <a class="menu-button icon-menu" href="index.html#"><span class="word">Menu</span></a>
    </nav>
</header>

<main class="content" role="main">
    <article class="post tag-ruby">

        <header class="post-header">
            <h1 class="post-title">Tips of exception handling in Ruby</h1>
            <section class="post-meta">
                <time class="post-date" datetime="2015-01-02">02 January 2015</time>  on <a href="../tag/ruby/">ruby</a>
            </section>
        </header>

        <section class="post-content">
            <p>In this post, I'd like to share with you some basic knowledge and tips about exception handling in Ruby.</p>

<h6 id="avoidingrescuewithexception">Avoiding rescue with Exception</h6>

<p>One common mistake when handling exceptions in Ruby is catching exceptions with an <code>Exception</code> instance, e.g <code>rescue Exception =&gt; e</code>.</p>

<p>The reason is very simple, let take a look at the Ruby Exception Hierarchy below: <br>
<img src="https://dl.dropboxusercontent.com/u/12981551/exception.jpg" alt="Ruby Exception Hierarchy">
As you see, <code>Exception</code> is the root of all exception / error classes in Ruby, which also includes <code>NoMemoryError</code>, <code>SyntaxError</code>, <code>Interrupt</code>, etc.</p>

<p>By rescuing with <code>Exception</code>, you may inadvertently allow code with wrong syntax being deployed, or prevent user terminating your program in <em>normal way</em>, like the example below:</p>

<pre><code class="language-ruby">while true do  
  begin
    line = STDIN.gets
    # heavy processing
  rescue Exception =&gt; e
    puts "caught exception #{e.class}! ohnoes!"
  end
end  
</code></pre>

<p>When running this in console, users are unable to stop it by using <code>CTRL + C</code>.</p>

<p>Therefore, you should use <code>StandardError</code> instead when catching general exceptions, which also have a shorthand syntax <code>rescue =&gt; e</code>.</p>

<p>You can check this <a href="http://daniel.fone.net.nz/blog/2013/05/28/why-you-should-never-rescue-exception-in-ruby/">blog post</a> for better understanding about this bad practice.</p>

<h6 id="customexception">Custom Exception</h6>

<p>We can define a custom exception class that inherit from the base class <code>Exception</code>, but usually we should inherit from <code>StandardError</code> or its subclasses:  </p>

<pre><code class="language-ruby">class MyCustomError &lt; StandardError; end  
</code></pre>

<p>We can also add additional attributes in our custom exception class to provide more context when handling the exception:  </p>

<pre><code class="language-ruby">class MyCustomError &lt; StandardError  
  attr_reader :object

  def initialize(object)
    @object = object
  end
end

# usage
begin  
  raise MyCustomError.new(user), 'Something broke'
rescue MyCustomError =&gt; e  
  e.object # =&gt; user
end  
</code></pre>

<h6 id="raiserescuesynonyms">raise / rescue synonyms</h6>

<p>Following are some common uses of <code>raise / rescue</code> with their synonymous forms which can explain them a little bit clearer.  </p>

<pre><code class="language-ruby">fail  
# is equivalent to
raise  
</code></pre>

<pre><code class="language-ruby">raise MyCustomError, 'Something broke'  
# is equivalent to
raise MyCustomError.new('Something broke')  
</code></pre>

<pre><code class="language-ruby">raise  
# is equivalent to
raise RuntimeError  
</code></pre>

<pre><code class="language-ruby">raise 'Something broke'  
# is equivalent to
raise RuntimeError, 'Something broke'  
</code></pre>

<pre><code class="language-ruby">begin  
rescue =&gt; e  
end  
# is equivalent to
begin  
rescue StandardError =&gt; e  
end  
</code></pre>

<h6 id="raiserescuevsthrowcatch">raise / rescue vs throw / catch</h6>

<p>The difference between <code>raise / rescue</code> and <code>throw / catch</code> has caused much confusion for ruby beginners, especially for those who came from Java or C++ background. </p>

<p>While <code>raise / rescue</code> is purely exception handling stuff for <em>exceptional circumstances</em>, <code>throw / catch</code> allow you to quick jump out of a block define by a specific symbol. </p>

<p>It come very handy if you want to break out of nested loops, for example:</p>

<pre><code class="language-ruby">found_person = nil  
catch(:found) do  
  people.each do |person|
    person.cars.each do |car|
      if car.name == 'Toyota Camry'
        found_person = person
        throw :found
      end
    end
  end
end  
</code></pre>

<p>In this example, we try to find the first person who own a Toyota Camry by looping through all cars of each person and stop right after we find the first car that matched.</p>

<p><code>throw</code> also accept a return value beside the identifying symbol, so the previous example could be rewritten as:</p>

<pre><code class="language-ruby">found_person = catch(:found) do  
  people.each do |person|
    person.cars.each do |car|
      throw(:found, person) if car.name == 'Toyota Camry'
    end
  end
end  
</code></pre>

<h6 id="shorthandsyntaxtorescueamethod">Shorthand syntax to rescue a method</h6>

<p>If you have some method like this:  </p>

<pre><code class="language-ruby">def some_method  
  begin
    do_something!
  rescue
    # handle exception
  end
end  
</code></pre>

<p>You can make it a little bit cleaner by rewriting it as following:  </p>

<pre><code class="language-ruby">def some_method  
  do_something!
rescue  
  # handle exception
end  
</code></pre>

<h6 id="references">References</h6>

<ul>
<li><a href="http://www.slideshare.net/snmaynard/ruby-rails-error-handling-18123823">http://www.slideshare.net/snmaynard/ruby-rails-error-handling-18123823</a></li>
<li><a href="http://phrogz.net/programmingruby/tut_exceptions.html">http://phrogz.net/programmingruby/tut_exceptions.html</a></li>
<li><a href="http://rubymonk.com/learning/books/4-ruby-primer-ascent/chapters/41-exceptions/lessons/93-throw-and-catch">http://rubymonk.com/learning/books/4-ruby-primer-ascent/chapters/41-exceptions/lessons/93-throw-and-catch</a></li>
</ul>
        </section>

        <footer class="post-footer">


            <figure class="author-image">
                <a class="img" href="../author/vinh/" style="background-image: url(http://www.gravatar.com/avatar/a8637bb35bf705a7a5e7f5e69c67b784?s&amp;)"><span class="hidden">Vinh Bach's Picture</span></a>
            </figure>

            <section class="author">
                <h4><a href="../author/vinh/">Vinh Bach</a></h4>

                    <p>Read <a href="../author/vinh/">more posts</a> by this author.</p>
                <div class="author-meta">
                    
                    
                </div>
            </section>


            <section class="share">
                <h4>Share this post</h4>
                <a class="icon-twitter" href="https://twitter.com/intent/tweet?text=Tips%20of%20exception%20handling%20in%20Ruby&amp;url=http://localhost:2368/tips-of-exception-handling-in-ruby/" onclick="window.open(this.href, 'twitter-share', 'width=550,height=235');return false;">
                    <span class="hidden">Twitter</span>
                </a>
                <a class="icon-facebook" href="https://www.facebook.com/sharer/sharer.php?u=http://localhost:2368/tips-of-exception-handling-in-ruby/" onclick="window.open(this.href, 'facebook-share','width=580,height=296');return false;">
                    <span class="hidden">Facebook</span>
                </a>
                <a class="icon-google-plus" href="https://plus.google.com/share?url=http://localhost:2368/tips-of-exception-handling-in-ruby/" onclick="window.open(this.href, 'google-plus-share', 'width=490,height=530');return false;">
                    <span class="hidden">Google+</span>
                </a>
            </section>


        </footer>

    </article>
</main>

<aside class="read-next">
    <a class="read-next-story no-cover" href="../common-security-mistakes-in-rails/">
        <section class="post">
            <h2>Common security mistakes in Rails</h2>
            <p>Rails is a mature web framework with a lot of improvements on security over time, but this doesn't mean…</p>
        </section>
    </a>
    <a class="read-next-story prev no-cover" href="../implement-paypal-reference-transactions-with-active-merchant/">
        <section class="post">
            <h2>Implement Paypal Reference transactions with Active Merchant</h2>
            <p>Reference transactions allow merchants to make subsequent transactions from a customer without the need to re-login into Paypal again.…</p>
        </section>
    </a>
</aside>



        <footer class="site-footer clearfix">
            <section class="copyright"><a href="../">A geeky corner</a> © 2016</section>
            <section class="poweredby">Proudly published with <a href="https://ghost.org">Ghost</a></section>
        </footer>

    </div>

    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    
    <script type="text/javascript" src="../assets/js/jquery.fitvids.js?v=d91b2f636f"></script>
    <script type="text/javascript" src="../assets/js/index.js?v=d91b2f636f"></script>

</body>
